### ISSUE TITLE
Classes should be in their own file

### ISSUE THREAD

**Issue by luiskhernandez** [cquinterom096/PlayScraper#2]
https://github.com/cquinterom096/PlayScraper/blob/6d649678b331302f5fa2d277cff798ba130ff3a4/main.rb#L35

https://github.com/cquinterom096/PlayScraper/blob/6d649678b331302f5fa2d277cff798ba130ff3a4/main.rb#L8

**Comment by cquinterom096** [comment]
Closed by @cquinterom096, classes moved to their own files.
